### ISSUE TITLE
easy-rsa does not have a gen-client-keys\conf script

### ISSUE THREAD

**Issue by chris-downs** [gate-sso/gate#10]
I cannot find a version of easy-rsa that contains the `gen-client-keys` and `gen-client-conf` scripts that are called in [profile_controller](https://github.com/gate-sso/gate/blob/master/app/controllers/profile_controller.rb#L23) when generating client VPN profiles. Do you know which version had this?

**Comment by chris-downs** [comment]
I'm going to try and modernize this to use easyrsa3. I'll open a PR when I get it working.

**Comment by ajeygore** [comment]
I am adding both scripts in this tree, please have a look.

**Comment by ajeygore** [comment]
I have added both scripts.
