### ISSUE TITLE
callback processing failing with undefined method 'new_session_path'

### ISSUE THREAD

**Issue by lanejlanej** [gate-sso/gate#11]
Hi, 

This may be a versioning thing.

I have gate-sso running fine as far as calling out to Google and perfoming the authentication.
But the callback fails with the following error:
I, [2017-06-22T13:40:05.585781 #28966]  INFO -- : Processing by Users::OmniauthCallbacksController#failure as HTML
I, [2017-06-22T13:40:05.585869 #28966]  INFO -- :   Parameters: {"state"=>"a71627ca1b391967fd1f1d31f24c910ce7242c0a3ace090b", "code"=>"4/5YdFdw-hglL9Ve76qMGwIFRaqQzJfqmM_qjDszWCsww"}
I, [2017-06-22T13:40:05.605512 #28966]  INFO -- : Completed 500 Internal Server Error in 20ms (ActiveRecord: 0.0ms)
F, [2017-06-22T13:40:05.609879 #28966] FATAL -- :
NoMethodError (undefined method `new_session_path' for #<Users::OmniauthCallbacksController:0x0055a61faf52d8>

I have tried adding following method (and varients) to application_controller.rb:
 def new_session_path(scope)
    new_user_session_path
  end
but it doesn't help.

I am running with the following gem versions:

devise (4.1.0)
omniauth (1.6.1)
omniauth-google-oauth2 (0.4.1)
omniauth-oauth2 (1.4.0)

Any help appreciated.

Thanks.

**Comment by malikid** [comment]
I ran into this yesterday, and just knew what I was missing. Though nothing mentioned on the doc, you need to enable Google+ API as well. But this error still should be fixed. It should skip the session part and return a failure page instead of a server crash.

**Comment by lanejlanej** [comment]
Hi, malikid

I tried enabling Google+ API as you suggested, but didn't make any difference.  No sign of any request trying to hit google+ api for the project. No sign of any changed behaviour at all in fact.

**Comment by ajeygore** [comment]
Can you update to lastest code and tell me if you are still having this error, there was version mismatch i have updated the gems.

**Comment by lanejlanej** [comment]
Hi Ajey,

Yes, that's fixed it.  I get logged in now and presented with QR code and
openvpn download button.  (Now just need to
work out how it is supposed to integrate with openvpn).

Thanks

John

**Comment by ajeygore** [comment]
Very simple. Install open VPN and point the scripts to easy RSA and you
should be good to go

**Comment by lanejlanej** [comment]
Hi Ajey,

Yes, sorted. Works great.
