### ISSUE TITLE
Restrict which users can create ovpn profile

### ISSUE THREAD

**Issue by gbobr** [gate-sso/gate#119]
I'm testing Gate to use it to create openvpn profiles for my google suite accounts, however, i don't wan't all the users in my google suite domain to be able to log in and download a profile.

I've read somewhere you mentioned SSAML support, can i use that feature to control access from my g suite user accounts?

**Comment by ajeygore** [comment]
We are putting SAML support, but if you don't want auto sign up, then we can introduce a feature for automatic vs manual enrolment, let me know what do you need?

**Comment by gbobr** [comment]
Thank you very much for your reply. I don't think that changing the enrollment will be necessary for now. I just wanted to know if there was any existing feature to support that.
