### ISSUE TITLE
Authentication credentials on some APIs

### ISSUE THREAD

**Issue by giosakti** [gate-sso/gate#126]
Currently on some APIs that is oftenly accessed, such as `nss` we're authenticating with personal access token.

Should we refactor it so that it also allows registered `api resources` with their `access key` to access `nss` API? 

Because personal token tied to user, while nss APIs are accessed by external services

**Comment by ajeygore** [comment]
Actually NSS APIs now use host based token - those are issued when host gets registered.

**Comment by giosakti** [comment]
Some are still not, for example this one on nss

```
...
def groups_list
    token = AccessToken.valid_token params[:token]
if token
...
```

that API is used by 3rd party services, such as portal to fetch a user groups
