### ISSUE TITLE
Easy Demo steps for non ruby experts

### ISSUE THREAD

**Issue by NunoPinheiro** [gate-sso/gate#132]
I'm trying to validate this solution. I would expect to be able to set up a demo in a few minutes, but have been trying to run the application for a few hours without success.
As a non ruby user I don't even know how to proceed to start the application.

There could be some docker/vragant/.sh script to setup with minimal effort, or at least a documentation on all the steps (e.g how do I start a dev server of the application locally?)

I've gone through the issues and found some documentation (e.g how to start a ruby app in digital ocean): https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04.
But I haven't been able to even test the application locally, so I am still not intending to invest on learning how to deploy a rails app.

**Comment by Rubueno** [comment]
@ajeygore I just started with this. Hoping for it to be what I expect it to be. I'm confused at which files I need to insert my configuration. And how do I start the application eventually?

**Comment by dthorntoncarrot** [comment]
Suggestion:

In the readme between "Finishing Setup" and "Additional Steps" please add a section called: start the server.

with the steps required to start the server.

Thanks

**Comment by ajeygore** [comment]
Thanks - and gate moved to https://github.com/gate-sso/gate-wireguard
