### ISSUE TITLE
OpenVPN auth integration with Gate

### ISSUE THREAD

**Issue by stoiev** [gate-sso/gate#137]
Hi!

I've setup a Gate box successfully and got an OpenVPN profile download page, as an admin (first user).
Nonetheless, I could not see a link between OpenVPN user authentication and the generated Gate user.

How does OpenVPN validates credentials and its OTP's in order to authenticate a Gate account? Should I configure a plugin on OpenVPN to call Gate or even Google Authenticator backend?

**Comment by misschak** [comment]
+1
It seems like after importing the user's profile to my openvpn client, it doesn't matter what username/password i put, openvpn does not seem to authenticate against google authenticator's pin. Is this the expected behaviour?

**Comment by ajeygore** [comment]
Hello Sorry to miss this out, are you guys still facing this problem, there are scripts under scripts directory which can help you with this.

**Comment by ajeygore** [comment]
I will get back to you with all the steps, give me few days, I think there is a need of auto setup for that.

**Comment by sassyn** [comment]
> I think that's not a problem, but a misuse.
> 
> Script directory file's just prepare client .ovpn file and keys, and set [auth-user-pass](https://github.com/gate-sso/gate/blob/master/scripts/gen-client-conf#L28) that force final user to fill openvpn credentials.
> 
> The issue is that I do not figured out which credential (user/password) is needed by the user, since there is no explicit integration between openvpn server and any auth backend. Does that integration must be manually configured (in PAM, with a gate plugin, or something like it)?



> I will get back to you with all the steps, give me few days, I think there is a need of auto setup for that.

Can you please provide the info regard this? 

I also missing how the VPNServer is doing the SAML auth...

Is the auth-user-pass is only used for the OTP? or also for the SAML? 
I understand that the first login, in order to download the VPN Client profile you have to do a authentication via the the g-suite account, but does it also in the OpenVPN server?

Thank You

**Comment by sassyn** [comment]
> Hi!
> 
> I've setup a Gate box successfully and got an OpenVPN profile download page, as an admin (first user).
> Nonetheless, I could not see a link between OpenVPN user authentication and the generated Gate user.
> 
> How does OpenVPN validates credentials and its OTP's in order to authenticate a Gate account? Should I configure a plugin on OpenVPN to call Gate or even Google Authenticator backend?

Did u ever manage to figure this out?

**Comment by sassyn** [comment]
> Hello Sorry to miss this out, are you guys still facing this problem, there are scripts under scripts directory which can help you with this.

Hi,

Did you have an answer for this?
Thank You

**Comment by ajeygore** [comment]
https://github.com/gate-sso/gate-wireguard Gate Moved to WireGuard
