### ISSUE TITLE
Stuck at rake app:setup

### ISSUE THREAD

**Issue by johnsonyick** [gate-sso/gate#146]
![Screenshot 2019-03-21 at 4 32 09 PM](https://user-images.githubusercontent.com/48547622/54741984-05f00000-4bfb-11e9-9fbb-d62af7234802.png)

I am new to gate-sso and ruby, i have tried to install all possible library but still got stuck at running rake app:setup

**Comment by ajeygore** [comment]
do you want Dev or Prod setup?

**Comment by ajeygore** [comment]
Also gate moved to https://github.com/gate-sso/gate-wireguard
