### ISSUE TITLE
VPN using SSO fails

### ISSUE THREAD

**Issue by krishnaastica** [gate-sso/gate#147]
Hi, 
Thanks for your effort in bringing GATE SSO. 
The first think I would like to mention is "It needs a better documentation" 
Anyways, I followed the Readme.MD and successfully completed the installation.
But I cannot connect to my OpenVPN-CE using the generated certs and profile.

Is something needs to be done? 
Should I configure PLUGIN for authentication in server.conf? 

Please suggest / help. 
-Thanks, 
Krishh

**Comment by ajeygore** [comment]
Please look at scripts folder, those scripts are required for OpenVPN Server to function

**Comment by ajeygore** [comment]
gate moved to wireguard https://github.com/gate-sso/gate-wireguard
