### ISSUE TITLE
Routes - No route matches [GET] "/vpn/users/auth/google_oauth2/callback"

### ISSUE THREAD

**Issue by DrIanGregory** [gate-sso/gate#196]
It makes sense to specify the url like this: http://example.com:4000/vpn. 
Not merely a base URL:  http://example.com:4000.
As the base url is probably used for other things.

A feature enhancement please is to allow for specifying a full url path please.

Thank you!

**Comment by ajeygore** [comment]
Please see https://github.com/gate-sso/gate-wireguard
