### ISSUE TITLE
[security] All apis can be accessed using one auth token

### ISSUE THREAD

**Issue by olttwa** [gate-sso/gate#24]
#### Description

- If one access token is leaked, all apis are compromised.
- Instead, keep one access token per api.

#### Acceptance Criteria

- One access token should authenticate only one api.
- Access token for an api shouldn't authenticate any other api.

**Comment by ajeygore** [comment]
This has been fixed, now only register host and authentication APIs are with common tokens, but rest all APIs are based on limited per user token.
