### ISSUE TITLE
Restricting VPN profile creation to certain users

### ISSUE THREAD

**Issue by nathanhinkle** [gate-sso/gate#49]
Hi! This may be a noob question.  Is it possible to restrict create of vpn profiles to only certain users if using Google Authentication?  I would like to have approved users be able to automatically have profiles created, but only approved users. Thanks!

**Comment by kingsly** [comment]
This is currently possible for IPSec IKEv2 VPNs but not for OpenVPN.

**Comment by ajeygore** [comment]
I am closing this issues, unless you want this to be done with OpenVPN, we will prioritise that in that case.
