### ISSUE TITLE
Implement Auto-complete drop down

### ISSUE THREAD

**Issue by ajeygore** [gate-sso/gate#81]
We need to provide "writeable" autocomplete drop down with scroll bar, instead of opening entire list, it should just provide place to type.

**Comment by giosakti** [comment]
Listing possible autocomplete fields:

- Users
  - Add Group
- Groups
  - Assign Admin
  - Add User
  - Add VPN
  - Add Host
- Hosts
  - Add VPN

I'll work on this

**Comment by ajeygore** [comment]
Thanks :-)

Also, we need to check Uniqueness of API name before it get’s submitted. You can’t have an API with duplicate name and there should be no spaces on [a-z][A-Z]_- is allowed

**Comment by ajeygore** [comment]
Yes, but that validates when it tries to save model, if we put this in javascript then life will be much easier, I will merge your pull request.

**Comment by giosakti** [comment]
ok, breakdown the tasks necessary for that:

- [ ] create internal API for checking uniqueness
- [ ] validate uniqueness on `.blur()`
- [ ] validate name using regex

**Comment by giosakti** [comment]
PR raised #90

**Comment by ajeygore** [comment]
Merged, closing this issue, Thanks.
