### ISSUE TITLE
Better profile page

### ISSUE THREAD

**Issue by detj** [gate-sso/gate#84]
The profile page is the first page any user (new or returning) sees. I'm referring to /profile.

## What do I have in mind?

Well, simple things to start with. Like

1. Fix typos. `Google Authenticator` instead of `Google Authentication`
2. Structure layout without the use of `<br>` tags, if possible
3. Provide links to Google Authenticator Play Store & App Store page
4. Fix the missing `if`
5. 👇 

**this**
![profile-before](https://user-images.githubusercontent.com/280236/36891382-778f2248-1e27-11e8-8222-e0b830c97ced.png)

vs

**this**
![profile-after](https://user-images.githubusercontent.com/280236/36891388-7b4cae32-1e27-11e8-88df-327753b443f1.png)

6. Make copy compatible with IPSec VPN, not just OpenVPN

Yeah, if done this. The profile page will be a tad bit better.

**Comment by detj** [comment]
Oh. And

4. Fix the missing `if`
5. this vs that

![profile-before](https://user-images.githubusercontent.com/280236/36891382-778f2248-1e27-11e8-8222-e0b830c97ced.png)
![profile-after](https://user-images.githubusercontent.com/280236/36891388-7b4cae32-1e27-11e8-88df-327753b443f1.png)

6. Make copy compatible with IPSec VPN, not just OpenVPN

**Comment by giosakti** [comment]
Raised PR #87 for this

Before
<img width="758" alt="before" src="https://user-images.githubusercontent.com/524078/36956577-c04bd63e-2061-11e8-97cf-5ef9c928bee5.png">

After
<img width="756" alt="after" src="https://user-images.githubusercontent.com/524078/36956585-ca51c008-2061-11e8-95b8-9f933be1d288.png">

**Comment by giosakti** [comment]
I think we can close this, @ajeygore merged #87

**Comment by detj** [comment]
Awesome! Can't wait to see this change land on production.

**Comment by ajeygore** [comment]
Your wait is over... :-) go check
