### ISSUE TITLE
host patterns is not wokring

### ISSUE THREAD

**Issue by Deepak1100** [gate-sso/gate#9]
Hi,

I am trying to set it up on my dev server. So up till now, everything works well apart from host pattern.
I have removed access to all host for a particular user and the groups it belongs too i.e host list is empty. 
But still that user able to access to that server.
Please let me know if I am missing something.

**Comment by vjdhama** [comment]
@Deepak1100 I will try to reproduce this issue.

cc/ @ajeygore @singhsankalp

**Comment by ajeygore** [comment]
Hi Deepak, Sorry for not responding to you earlier, are you trying to login using MFA or trying to use authorized keys command file

**Comment by Deepak1100** [comment]
Hi Ajey,
I am trying authorized keys command file.

**Comment by ajeygore** [comment]
Authorised keys command will need a token to be created in databases.

**Comment by Deepak1100** [comment]
I have created token and hence login was working but not host patterns...

**Comment by ajeygore** [comment]
Let me check. Get back to me.

**Comment by ajeygore** [comment]
Authorised keys comand works without restriction apparently right now. I am fixing it.
