### ISSUE TITLE
Flash message shown at wrong place

### ISSUE THREAD

**Issue by detj** [gate-sso/gate#98]
*Signed out successfully* message shows up at an incorrect time & place.

![gate gojek co id_api_resources_new](https://user-images.githubusercontent.com/280236/37449752-87076530-2851-11e8-9a93-909c55a3a32f.png)

## Steps to reproduce

1. Login
2. Sign out
3. Login again
4. Navigate to `/api_resources/new`

## Expected behavior

Maybe it just doesn't make sense to show this message anywhere. The signout operation anyways performs a redirect and lands the user on the (logged-out) landing screen. So, for a user its quite clear, that sign out was a success.

**Comment by ajeygore** [comment]
This has been fixed.
